name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "sakura-test"
database_id = "103ffdd3-2466-4d86-95bc-39b0a4681614"

[version_metadata]
binding = "CF_VERSION_METADATA"
